export const categories = [
  {
    name: "Sneakers",
    slug: "sneakers",
    description:
      "Discover the Muroexe sneakers collection on our website. Vegan sneakers at the best price and with a wide range of models available. Maximum comfort and flexibility.",
    image: "https://i.ibb.co/mc0szSV/c-Sneakers.jpg",
  },
  {
    name: "Shoes",
    slug: "shoes",
    description:
      "Muroexe shoe collection: comfortable, technical and elegant, at the best price. Unisex ecological footwear with a huge variety of models available. 100% cruelty free.",
    image: "https://i.ibb.co/6XBxh4W/c-Shoes.jpg",
  },
  {
    name: "Slippers",
    slug: "slippers",
    description:
      "Enjoy the comfort of Muroexe slippers. Ecological slippers for women and men with great comfort and flexibility.",
    image: "https://i.ibb.co/8Y14frC/c-Slippers.jpg",
  },
  {
    name: "Accessories",
    slug: "accessories",
    description:
      "Discover the Muroexe accessories collection on our website. Accessories, bags, backpacks, wallets and much more! Unisex and 100% cruelty free.",
    image: "https://i.ibb.co/zGjd3tg/c-Accessories.jpg",
  },
];

export const subcategories = [
  {
    name: "Bags",
    slug: "bags",
    category: "632836afe94708d5c652ca27",
  },
  {
    name: "Wallets",
    slug: "wallets",
    category: "632836afe94708d5c652ca27",
  },
];

export const users = [
  {
    name: "Admin",
    email: "admin@example.com",
    password: "123456",
    passwordConfirmation: "123456",
    role: "admin",
  },
  {
    name: "user1",
    email: "user1@example.com",
    password: "123456",
    passwordConfirmation: "123456",
    role: "user",
  },
  {
    name: "user2",
    email: "user2@example.com",
    password: "123456",
    passwordConfirmation: "123456",
    role: "user",
  },
  {
    name: "user3",
    email: "user3@example.com",
    password: "123456",
    passwordConfirmation: "123456",
    role: "user",
  },
];

export const brands = [
  {
    name: "Nike",
    slug: "nike",
    image: "https://i.ibb.co/whzTBd6/Br-nike.png",
  },
  {
    name: "Adidas",
    slug: "adidas",
    image: "https://i.ibb.co/84PZqmH/Br-adidas.png",
  },
  {
    name: "Puma",
    slug: "puma",
    image: "https://i.ibb.co/4K7x86H/Br-puma.png",
  },
  {
    name: "Converse",
    slug: "converse",
    image: "https://i.ibb.co/YybmgF1/Br-converse.png",
  },
  {
    name: "Reebok",
    slug: "reebok",
    image: "https://i.ibb.co/yFky4S3/Br-reebook.png",
  },
];

export const products = [
  //Category : Shoes=> Id=63292e769de7cef23355a195
  //Without Subcategories
  {
    name: "Atom Ochre Boot",
    slug: "atom-ochre-boot",
    image: "https://i.ibb.co/3hs1ZC9/alpha-boot-black.jpg",
    category: "63292e769de7cef23355a195",
    price: 300,
    priceAfterDiscount: 222,
    qtyInStock: 0,
    ratingAvr: 4,
    numReviews: 20,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Alpha Boot Brown",
    slug: "alpha-boot-brown",
    image: "https://i.ibb.co/C5H64jd/alpha-boot-brown.jpg",
    category: "63292e769de7cef23355a195",
    price: 120,
    qtyInStock: 5,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Alpha Boot Black",
    slug: "alpha-boot-black",
    image: "https://i.ibb.co/c8q2Z3B/army-boot-black.jpg",
    category: "63292e769de7cef23355a195",
    price: 350,
    priceAfterDiscount: 222,
    qtyInStock: 10,
    ratingAvr: 4,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Army Boot Black",
    slug: "army-boot-black",
    image: "https://i.ibb.co/sHtvHZP/army-boot-blue.jpg",
    category: "63292e769de7cef23355a195",
    price: 1900,
    qtyInStock: 20,
    ratingAvr: 2,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Ucon Black",
    slug: "ucon-black",
    image: "https://i.ibb.co/n0fNHNf/army-boot-ochre.jpg",
    category: "63292e769de7cef23355a195",
    price: 564,
    qtyInStock: 32,
    ratingAvr: 5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Atom Black Boot",
    slug: "atom-black-boot",
    image: "https://i.ibb.co/4Zwk1rg/atom-brown-boot.jpg",
    category: "63292e769de7cef23355a195",
    price: 354,
    priceAfterDiscount: 222,
    qtyInStock: 12,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Army Boot Blue",
    slug: "army-boot-blue",
    image: "https://i.ibb.co/85WQ8qK/atom-grey-boot.jpg",
    category: "63292e769de7cef23355a195",
    price: 300,
    qtyInStock: 8,
    ratingAvr: 5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Atom Gray Boot",
    slug: "atom-gray-boot",
    image: "https://i.ibb.co/nrkjbJv/atom-mist-beige.jpg",
    category: "63292e769de7cef23355a195",
    price: 350,
    qtyInStock: 7,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Alpha Army Boot",
    slug: "alpha-army-boot",
    image: "https://i.ibb.co/kHrFBzh/atom-ochre-boot.jpg",
    category: "63292e769de7cef23355a195",
    price: 789,
    priceAfterDiscount: 222,
    qtyInStock: 3,
    ratingAvr: 4,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Atom Mist Blue",
    slug: "atom-mist-blue",
    image: "https://i.ibb.co/NYDjx8X/meteor-black-1.jpg",
    category: "63292e769de7cef23355a195",
    price: 456,
    qtyInStock: 2,
    ratingAvr: 1,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Atom Mist Gray",
    slug: "atom-mist-gray",
    image: "https://i.ibb.co/YZfLnc2/meteor-blue.jpg",
    category: "63292e769de7cef23355a195",
    price: 190,
    qtyInStock: 12,
    ratingAvr: 4,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Marathon Black Boot",
    slug: "marathon-black-boot",
    image: "https://i.ibb.co/nrkjbJv/atom-mist-beige.jpg",
    category: "63292e769de7cef23355a195",
    price: 600,
    priceAfterDiscount: 222,
    qtyInStock: 0,
    ratingAvr: 2.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  //Category : Sneakers=> Id=63292e769de7cef23355a194
  //Without Subcategories
  {
    name: "alaska grey",
    slug: "alaska-grey",
    image: "https://i.ibb.co/syCVgMk/alaska-grey.jpg",
    category: "63292e769de7cef23355a194",
    price: 200,
    qtyInStock: 0,
    ratingAvr: 2.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "alpha carbono dark red",
    slug: "alpha-carbono-dark-red",
    image: "https://i.ibb.co/QpyjB5b/alpha-carbono-dark-red.jpg",
    category: "63292e769de7cef23355a194",
    price: 220,
    qtyInStock: 7,
    ratingAvr: 2.7,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "alpha neo beige",
    slug: "alpha-neo-beige",
    image: "https://i.ibb.co/JrFnQXm/alpha-neo-beige.png",
    category: "63292e769de7cef23355a194",
    price: 280,
    priceAfterDiscount: 222,
    qtyInStock: 3,
    ratingAvr: 4.8,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "alpha neo dark grey",
    slug: "alpha-neo-dark-grey",
    image: "https://i.ibb.co/nPTR26h/alpha-neo-dark-grey.png",
    category: "63292e769de7cef23355a194",
    price: 400,
    qtyInStock: 4,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "alpha neo pink",
    slug: "alpha-neo-pink",
    image: "https://i.ibb.co/bs4xktd/alpha-neo-pink.jpg",
    category: "63292e769de7cef23355a194",
    price: 600,
    priceAfterDiscount: 222,
    qtyInStock: 12,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "army blue",
    slug: "army-blue",
    image: "https://i.ibb.co/Gxz7JWC/army-blue.jpg",
    category: "63292e769de7cef23355a194",
    price: 788,
    qtyInStock: 12,
    ratingAvr: 2.9,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "army grey",
    slug: "army-grey",
    image: "https://i.ibb.co/Ln7V3Cn/army-grey.jpg",
    category: "63292e769de7cef23355a194",
    price: 650,
    qtyInStock: 0,
    ratingAvr: 2.2,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "atom oasis orange",
    slug: "atom-oasis-orange",
    image: "https://i.ibb.co/Xt9Rt62/atom-oasis-orange.png",
    category: "63292e769de7cef23355a194",
    price: 400,
    qtyInStock: 0,
    ratingAvr: 4.6,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "atom oasis red",
    slug: "atom-oasis-red",
    image: "https://i.ibb.co/Xx8QRkw/atom-oasis-red.png",
    category: "63292e769de7cef23355a194",
    price: 6000,
    priceAfterDiscount: 3000,
    qtyInStock: 10,
    ratingAvr: 5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "density blue",
    slug: "density-blue",
    image: "https://i.ibb.co/n0mtb3r/density-blue.jpg",
    category: "63292e769de7cef23355a194",
    price: 710,
    priceAfterDiscount: 222,
    qtyInStock: 22,
    ratingAvr: 2.8,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "hybrid black",
    slug: "hybrid-black",
    image: "https://i.ibb.co/YPS8pHj/hybrid-black.jpg",
    category: "63292e769de7cef23355a194",
    price: 1200,
    priceAfterDiscount: 900,
    qtyInStock: 0,
    ratingAvr: 2.4,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "juno cloud blue",
    slug: "juno-cloud-blue",
    image: "https://i.ibb.co/NY37gZd/juno-cloud-blue.jpg",
    category: "63292e769de7cef23355a194",
    price: 1900,
    priceAfterDiscount: 1500,
    qtyInStock: 7,
    ratingAvr: 3,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  //Category : Slippers=> Id=63292e769de7cef23355a196
  //Without Subcategories
  {
    name: "home mood black",
    slug: "home-mood-black",
    image: "https://i.ibb.co/M2JDL6M/home-mood-black.png",
    category: "63292e769de7cef23355a196",
    price: 900,
    qtyInStock: 20,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "home mood blue",
    slug: "home-mood-blue",
    image: "https://i.ibb.co/8dRm9qp/home-mood-blue.png",
    category: "63292e769de7cef23355a196",
    price: 300,
    qtyInStock: 4,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "slipper grey",
    slug: "slipper-grey",
    image: "https://i.ibb.co/W28M1rK/slipper-grey.jpg",
    category: "63292e769de7cef23355a196",
    price: 400,
    qtyInStock: 0,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  //Category : Accessories=> Id=63292e769de7cef23355a197
  //with Subcategories ["63292e779de7cef23355a199","63292e779de7cef23355a19a"]
  {
    name: "Block Beige",
    slug: "block-beige",
    image: "https://i.ibb.co/PZCYprP/block-beige.jpg",
    category: "63292e769de7cef23355a197",
    price: 500,
    priceAfterDiscount: 222,
    qtyInStock: 0,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a199"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Block Black",
    slug: "block-black",
    image: "https://i.ibb.co/W2GQbfT/block-black.jpg",
    category: "63292e769de7cef23355a197",
    price: 600,
    qtyInStock: 2,
    ratingAvr: 5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a199"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Block Blue",
    slug: "block-blue",
    image: "https://i.ibb.co/48CxTX8/block-blue.jpg",
    category: "63292e769de7cef23355a197",
    price: 790,
    qtyInStock: 3,
    ratingAvr: 2.7,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a199"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Suite Blue",
    slug: "suite-blue",
    image: "https://i.ibb.co/HzQxnHF/suite-blue.jpg",
    category: "63292e769de7cef23355a197",
    price: 300,
    qtyInStock: 0,
    ratingAvr: 4,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a199"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "Suite Grape",
    slug: "suite-grape",
    image: "https://i.ibb.co/K5T67yg/suite-grape.jpg",
    category: "63292e769de7cef23355a197",
    price: 450,
    priceAfterDiscount: 222,
    qtyInStock: 9,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a199"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "The pocket XBlack",
    slug: "the-pocket-x-black",
    image: "https://i.ibb.co/MM5B67D/pocket-x-black.jpg",
    category: "63292e769de7cef23355a197",
    price: 120,
    qtyInStock: 0,
    ratingAvr: 5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a19a"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "The pocket YBlack",
    slug: "the-pocket-y-black",
    image: "https://i.ibb.co/qCmsDb6/pocket-y-black.jpg",
    category: "63292e769de7cef23355a197",
    price: 140,
    qtyInStock: 7,
    ratingAvr: 4.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a19a"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "The pocket Beige",
    slug: "the-pocket-beige",
    image: "https://i.ibb.co/jbjfc2y/pocket-x-beige.jpg",
    category: "63292e769de7cef23355a197",
    price: 400,
    qtyInStock: 8,
    ratingAvr: 2.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a19a"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
  {
    name: "The pocket Blue",
    slug: "the-pocket-blue",
    image: "https://i.ibb.co/bXWLrGj/pocket-y-blue.jpg",
    category: "63292e769de7cef23355a197",
    price: 600,
    priceAfterDiscount: 222,
    qtyInStock: 12,
    ratingAvr: 3.5,
    numReviews: 3,
    size: ["38", "40", "42", "48"],
    subcategories: ["63292e779de7cef23355a19a"],
    description:
      "With Alpha Boot we wanted to reinvent the classic trekking boot but with a much lighter, urban and comfortable sole. All this is due to the implementation of our latest sole: Alpha, with which we have achieved optimal grip, no matter the situation. In addition, thanks to its waxed microfiber surface, PU and its internal mesh lining, it makes it perfect for winter and the inclemency of your day to day in the city. The future of trekking boots is here.",
  },
];
